version: '3.8'

services:
  inpoin-rest-api:
    container_name: inpoin-rest-api
    image: kevinjanada/inpoin-rest-api:latest
    env_file:
      - .env
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - inpoin
    restart: unless-stopped
    volumes:
      - wallet:/usr/src/app/wallet
      - organizations:/usr/src/app/organizations

networks:
  inpoin:

volumes:
  wallet:
  organizations:
